# -*- coding: utf-8 -*-
"""detect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12KWKNVDYJQOXRL-5uvcxb7Fq4Ts2jF9a
"""

!pip install cmake dlib face_recognition numpy opencv-python

!pip install opencv-python

from google.colab import drive
drive.mount('/gdrive/')

# Commented out IPython magic to ensure Python compatibility.
# %cd /gdrive/My Drive/face-detection

ls

import cv2
from google.colab.patches import cv2_imshow

image=cv2.imread("ishu.jpg")

cv2_imshow(image)

cv2.imwrite('xyz.jpg',image)

ls

gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

cv2_imshow(gray)

hsv=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)

cv2_imshow(hsv)

image=cv2.resize(image,(250,250))
cv2_imshow(image)

rows,cols=image.shape[ :2]

m=cv2.getRotationMatrix2D((cols/2,rows/2),180,1)
dist=cv2.warpAffine(image,m,(cols,rows))

cv2_imshow(dist)

import numpy as np
m=np.float32([[1,0,-100],[0,1,-100]])
dist=cv2.warpAffine(image,m,(cols,rows))
cv2_imshow(dist)



img=cv2.imread("ishu.jpg")
cv2_imshow(img)

img=cv2.resize(img,(250,250))
cv2_imshow(img)

edge=cv2.Canny(img,150,500)
cv2_imshow(edge)

import face_recognition

loc=face_recognition.face_locations(img)
loc

cv2.rectangle(img,(79,56),(187,163),(255,0,0),2)
cv2.putText(img,"sowndarya",(79,56),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2)

cv2_imshow(img)

features=face_recognition.face_landmarks(image)
features

ls

image=cv2.imread("nagsam.jpg")
cv2_imshow(image)

known=face_recognition.load_image_file("ishu.jpg")
unknown=face_recognition.load_image_file("frnd.jpg")



known_en=face_recognition.face_encodings(known)[0]
unknown_en=face_recognition.face_encodings(unknown)[0]

known_en

results=face_recognition.compare_faces([known_en],unknown_en)

results

distance=face_recognition.face_distance([known_en],unknown_en)
distance

# Commented out IPython magic to ensure Python compatibility.
# %ls